import { useEffect, useRef, useState, type FormEvent, type ReactNode } from "react";
import { ArrowDownToLine, ArrowRight, ArrowUpRight, CalendarDays, Check, CheckCheck, ChevronRight, CircleHelp, Clock3, CreditCard, Eye, LayoutDashboard, LockKeyhole, MapPin, MessageCircle, Pencil, Search, Send, ShieldCheck, SlidersHorizontal, Target, UserRound, Wallet, X } from "lucide-react";
import { BrandMark } from "../shared/ui/BrandMark";
import johnPhoto from "../assets/trainers/john-kim.png";
import { createLeads, dateLabel, inPeriod, INITIAL_PROFILE, money, STAGE_LABELS, TODAY, UNLOCK_PRICE, type Lead, type LeadStage, type Profile } from "./fixture";

type Page = "overview" | "enquiries" | "profile" | "spending";
type Filter = "all" | LeadStage;
type Scenario = "populated" | "empty" | "error";
const NAV = [{ id: "overview", label: "Overview", icon: LayoutDashboard }, { id: "enquiries", label: "Enquiries", icon: MessageCircle }, { id: "profile", label: "My profile", icon: UserRound }, { id: "spending", label: "Spending", icon: Wallet }] as const;
const PAGE_COPY = { overview: ["Good morning, John", "A little less admin. More time to coach."], enquiries: ["Your enquiries", "Get to know the people who want to train with you."], profile: ["Your trainer profile", "Help the right people find you."], spending: ["Your unlock spending", "Keep track of what you spend finding new clients."] };

export function TrainerDashboard() {
  const [page, setPage] = useState<Page>("overview");
  const [leads, setLeads] = useState(createLeads);
  const [profile, setProfile] = useState<Profile>(INITIAL_PROFILE);
  const [profileDraft, setProfileDraft] = useState<Profile>(INITIAL_PROFILE);
  const [submitted, setSubmitted] = useState(false);
  const [period, setPeriod] = useState(28);
  const [filter, setFilter] = useState<Filter>("all");
  const [query, setQuery] = useState("");
  const [scenario, setScenario] = useState<Scenario>("populated");
  const [selected, setSelected] = useState<string | null>(null);
  const [previewProfile, setPreviewProfile] = useState(false);
  const [help, setHelp] = useState(false);
  const [toast, setToast] = useState("");
  const content = useRef<HTMLElement>(null);
  const visibleLeads = scenario === "empty" ? [] : leads;
  const periodLeads = visibleLeads.filter(lead => inPeriod(lead.created, period));
  const newLeads = periodLeads.filter(lead => lead.stage === "new");
  const replyLeads = periodLeads.filter(lead => lead.stage === "reply");
  const unlocks = periodLeads.filter(lead => lead.unlocked);
  const transactions = visibleLeads.filter(lead => lead.unlockedAt && inPeriod(lead.unlockedAt, period));
  const wins = periodLeads.filter(lead => lead.stage === "won");
  const currentLead = visibleLeads.find(lead => lead.id === selected);
  const profileToPreview = page === "profile" ? profileDraft : profile;
  const followUps = visibleLeads.filter(lead => lead.followUp && !["closed", "won"].includes(lead.stage)).sort((a, b) => a.followUp!.localeCompare(b.followUp!));
  const openPage = (next: Page, nextFilter: Filter = "all") => { setPage(next); setFilter(nextFilter); setQuery(""); content.current?.scrollTo({ top: 0 }); };
  const updateLead = (id: string, patch: Partial<Lead>) => setLeads(current => current.map(lead => lead.id === id ? { ...lead, ...patch } : lead));
  useEffect(() => { if (!toast) return; const timer = window.setTimeout(() => setToast(""), 5000); return () => window.clearTimeout(timer); }, [toast]);
  const exportSpending = () => {
    const rows = [["Date", "Enquiry", "Amount GBP", "Status"], ...transactions.map(lead => [lead.unlockedAt!, lead.name, String(UNLOCK_PRICE), "Paid (sample)"])];
    const csv = rows.map(row => row.map(cell => `"${cell.replaceAll('"', '""')}"`).join(",")).join("\r\n");
    const url = URL.createObjectURL(new Blob([csv], { type: "text/csv;charset=utf-8" }));
    const link = document.createElement("a"); link.href = url; link.download = "petey-sample-unlock-spending.csv"; link.click(); URL.revokeObjectURL(url);
    setToast("Sample spending statement downloaded.");
  };

  return <div className="td-app">
    <a className="td-skip" href="#dashboard-content">Skip to dashboard</a>
    <div className="td-preview-bar"><span><span className="td-preview-dot" /> Interactive wireframe <span className="td-preview-detail">· Sample data · 9 Sep 2026 · No real charges or messages</span></span><label>Preview state <select aria-label="Preview state" value={scenario} onChange={e => { setScenario(e.target.value as Scenario); setSelected(null); }}><option value="populated">Active trainer</option><option value="empty">New trainer</option><option value="error">Loading error</option></select></label></div>
    <header className="td-topbar">
      <button className="td-brand" aria-label="Petey trainer overview" onClick={() => openPage("overview")}><BrandMark /><span>for trainers</span></button>
      <nav aria-label="Trainer navigation">{NAV.map(({ id, label, icon: Icon }) => <button key={id} aria-current={page === id ? "page" : undefined} className={page === id ? "is-active" : ""} onClick={() => openPage(id)}><Icon size={17} /><span>{label}</span>{id === "enquiries" && newLeads.length > 0 && <span className="td-nav-count">{newLeads.length}</span>}</button>)}</nav>
      <button className="td-user" aria-label="Edit John’s profile" onClick={() => openPage("profile")}><img src={johnPhoto} alt="" /><span>John Kim</span><ChevronRight size={15} /></button>
    </header>
    <main className="td-scroll" id="dashboard-content" tabIndex={-1} ref={content}>
      <div className="td-page">
        <div className="td-page-heading"><div><h1>{PAGE_COPY[page][0]}{page === "overview" && <span className="td-heading-dot">.</span>}</h1><p>{page === "overview" ? `${newLeads.length} new enquiries and ${replyLeads.length} leads awaiting your reply.` : PAGE_COPY[page][1]}</p></div>
          {page === "profile" ? <button className="td-button td-button--white" onClick={() => setPreviewProfile(true)}><Eye size={16} /> Preview profile</button> : <label className="td-period"><CalendarDays size={16} /><select aria-label="Reporting period" value={period} onChange={e => setPeriod(Number(e.target.value))}><option value={28}>Last 28 days</option><option value={7}>Last 7 days</option></select></label>}
        </div>
        {scenario === "error" ? <div className="td-empty td-error"><CircleHelp size={32} /><h2>Your dashboard couldn’t load</h2><p>Try again to pick up where you left off.</p><button className="td-button" onClick={() => setScenario("populated")}>Try again <ArrowRight size={16} /></button></div> : <>
          {page === "overview" && <div className="td-overview">
            <div className="td-primary">
              <div className="td-summary-grid">
                <section className="td-profile-card">
                  <div className="td-panel-top"><span>Your profile</span><button className="td-icon-button" aria-label="Edit profile" onClick={() => openPage("profile")}><Pencil size={16} /></button></div>
                  <div className="td-portrait"><img src={johnPhoto} alt="John Kim" /><span aria-label="Verified trainer"><ShieldCheck size={18} /></span></div>
                  <h2>{profile.name}</h2><p>{profile.specialty}</p><span className="td-location"><MapPin size={13} />{profile.area}</span>
                  <button className={`td-availability ${profile.accepting ? "" : "is-paused"}`} aria-pressed={profile.accepting} onClick={() => { const accepting = !profile.accepting; setProfile({ ...profile, accepting }); setProfileDraft({ ...profileDraft, accepting }); setToast(accepting ? "Preview: profile is accepting enquiries again." : "Preview: new enquiries paused. Existing leads stay available."); }}><span />{profile.accepting ? "Accepting new clients" : "New enquiries paused"}<SlidersHorizontal size={13} /></button>
                  <button className="td-text-button" onClick={() => setPreviewProfile(true)}>View public profile <ArrowUpRight size={14} /></button>
                </section>
                <button className="td-metric td-metric--lime" onClick={() => openPage("enquiries", "new")}><span className="td-metric-top">New enquiries<span className="td-metric-icon"><MessageCircle size={21} /></span></span><span className="td-metric-number">{newLeads.length.toString().padStart(2, "0")}</span><span className="td-metric-description">People ready to meet you</span><span className="td-metric-footer">Review & unlock <ArrowUpRight size={19} /></span></button>
                <button className="td-metric td-metric--dark" onClick={() => openPage("enquiries", "reply")}><span className="td-metric-top">Ready for your reply<span className="td-metric-icon"><Send size={21} /></span></span><span className="td-metric-number">{replyLeads.length.toString().padStart(2, "0")}</span><span className="td-metric-description">Unlocked, awaiting your first hello</span><span className="td-metric-footer">Start a conversation <ArrowUpRight size={19} /></span></button>
                <div className="td-funnel" aria-label={`Enquiries received in the last ${period} days`}><span><strong>{periodLeads.length}</strong> enquiries</span><ChevronRight size={16} /><span><strong>{unlocks.length}</strong> unlocked</span><ChevronRight size={16} /><span><strong>{wins.length}</strong> started training</span><span className="td-funnel-period">{period} days</span></div>
              </div>
              <section className="td-section td-enquiry-section"><SectionHeading title="Your newest enquiries" subtitle="See the fit before you unlock the conversation." action={<button className="td-text-button" onClick={() => openPage("enquiries", "new")}>View all <ArrowRight size={15} /></button>} />
                {newLeads.length ? <div className="td-lead-list">{newLeads.slice(0, 3).map(lead => <LeadRow key={lead.id} lead={lead} onOpen={() => setSelected(lead.id)} />)}</div> : <EmptyLeads onProfile={() => openPage("profile")} />}
              </section>
              <ActivityChart leads={periodLeads} period={period} />
            </div>
            <aside className="td-rail">
              <section><SectionHeading title="Your follow-ups" subtitle="Your upcoming reminders · All dates" action={<span className="td-round-icon"><CalendarDays size={18} /></span>} />
                <div className="td-followups">{followUps.length ? followUps.slice(0, 3).map(lead => <button key={lead.id} className="td-followup" onClick={() => setSelected(lead.id)}><span className="td-followup-date">{dateLabel(lead.followUp!)}<Clock3 size={13} /></span><span className="td-followup-body"><strong>{lead.name}</strong><span>{lead.note || "Follow up on their enquiry."}</span><small>{STAGE_LABELS[lead.stage]}</small></span><ArrowUpRight size={17} /></button>) : <p className="td-quiet-empty">You’re all caught up. Add a reminder to an unlocked enquiry when you need one.</p>}</div>
                {followUps.length > 0 && <button className="td-text-button td-rail-link" onClick={() => openPage("enquiries")}>Open your enquiries <ArrowRight size={15} /></button>}
              </section>
              <section className="td-spend-summary"><SectionHeading title="Lead outcomes" subtitle={`Enquiries received in the last ${period} days`} />
                <div className="td-conversion"><strong>{unlocks.length ? Math.round(wins.length / unlocks.length * 100) : "—"}{unlocks.length > 0 && <span>%</span>}</strong><span>of unlocked leads<br />started training</span></div>
                <div className="td-segment-bar" aria-hidden="true">{Array.from({ length: 16 }, (_, i) => <span className={i < (unlocks.length ? wins.length / unlocks.length * 16 : 0) ? "is-filled" : ""} key={i} />)}</div><p className="td-footnote">{wins.length} of {unlocks.length} unlocked leads · Outcomes marked by you</p>
                <dl className="td-mini-stats"><div><dt>Unlock spend</dt><dd>{money(transactions.length * UNLOCK_PRICE)}</dd></div><div><dt>Average per unlock</dt><dd>{transactions.length ? money(UNLOCK_PRICE) : "—"}</dd></div></dl>
                <button className="td-text-button" onClick={() => openPage("spending")}>View spending <ArrowRight size={15} /></button>
              </section>
              <section className="td-demand"><SectionHeading title="What people need" subtitle={`Goals in your ${periodLeads.length} recent enquiries`} />{["Run my first 10K", "Build strength", "Get back into fitness", "Improve my 5K time"].map(goal => { const count = periodLeads.filter(lead => lead.goal === goal).length; return <div className="td-demand-row" key={goal}><span>{goal}</span><strong>{count}</strong><div><span style={{ width: `${periodLeads.length ? count / periodLeads.length * 100 : 0}%` }} /></div></div>; })}</section>
              <button className="td-help-link" onClick={() => setHelp(true)}><CircleHelp size={16} /> How enquiries & unlocks work <ArrowUpRight size={14} /></button>
            </aside>
          </div>}

          {page === "enquiries" && <section className="td-inbox">
            <div className="td-inbox-tools"><div className="td-filter-tabs" aria-label="Filter enquiries">{(["all", "new", "reply", "contacted", "consultation", "won", "closed"] as Filter[]).map(stage => <button key={stage} aria-pressed={filter === stage} className={filter === stage ? "is-active" : ""} onClick={() => setFilter(stage)}>{stage === "all" ? "All enquiries" : STAGE_LABELS[stage]}<span>{periodLeads.filter(lead => stage === "all" || lead.stage === stage).length}</span></button>)}</div><label className="td-search"><Search size={17} /><input type="search" aria-label="Search enquiries" placeholder="Search name, goal or area" value={query} onChange={e => setQuery(e.target.value)} /></label></div>
            <div className="td-inbox-labels"><span>Person & goal</span><span>Budget & location</span><span>Received</span><span>Status</span></div>
            {periodLeads.filter(lead => (filter === "all" || lead.stage === filter) && `${lead.name} ${lead.goal} ${lead.area}`.toLowerCase().includes(query.toLowerCase())).map(lead => <LeadRow key={lead.id} lead={lead} expanded onOpen={() => setSelected(lead.id)} />)}
            {!periodLeads.some(lead => (filter === "all" || lead.stage === filter) && `${lead.name} ${lead.goal} ${lead.area}`.toLowerCase().includes(query.toLowerCase())) && <div className="td-empty"><MessageCircle size={30} /><h2>{visibleLeads.length ? "No enquiries in this view" : "Your next client starts here"}</h2><p>{visibleLeads.length ? "Try another status, search or reporting period." : "We’ll let you know when someone chooses you and sends an enquiry."}</p><button className="td-button" onClick={() => visibleLeads.length ? (setFilter("all"), setQuery(""), setPeriod(28)) : openPage("profile")}>{visibleLeads.length ? "Show all enquiries" : "Review my profile"}<ArrowRight size={16} /></button></div>}
            <p className="td-footnote td-inbox-note">An enquiry means someone chose to contact you. Unlock once to read their message and reply. Example unlock price: {money(UNLOCK_PRICE)}.</p>
          </section>}

          {page === "profile" && <ProfileEditor profile={profileDraft} setProfile={setProfileDraft} submitted={submitted} onSave={() => setToast("Profile draft saved for this preview session.")} onSubmit={() => { setSubmitted(true); setToast("Preview: changes submitted for review. Your current public profile stays live."); }} onPreview={() => setPreviewProfile(true)} />}

          {page === "spending" && <div className="td-spending-page"><div className="td-spending-metrics"><section><span>Unlock spend</span><strong>{money(transactions.length * UNLOCK_PRICE)}</strong><small>Payments in the last {period} days</small></section><section><span>Paid unlocks</span><strong>{transactions.length}</strong><small>One payment per enquiry</small></section><section><span>Average cost per unlock</span><strong>{transactions.length ? money(UNLOCK_PRICE) : "—"}</strong><small>Sample pricing, inclusive total</small></section></div>
            <div className="td-spending-content"><section className="td-transactions"><SectionHeading title="Unlock history" subtitle="Your record of each enquiry you chose to unlock." action={<button className="td-button td-button--white" onClick={exportSpending}><ArrowDownToLine size={16} /> Export CSV</button>} />{transactions.length ? transactions.sort((a, b) => b.unlockedAt!.localeCompare(a.unlockedAt!)).map(lead => <div className="td-transaction" key={lead.id}><span className="td-round-icon"><LockKeyhole size={16} /></span><span><strong>{lead.name}</strong><small>Enquiry unlock · {dateLabel(lead.unlockedAt!)}</small></span><span className="td-status td-status--won"><Check size={12} /> Paid</span><strong>{money(UNLOCK_PRICE)}</strong></div>) : <p className="td-quiet-empty">You haven’t unlocked any enquiries in this period.</p>}</section>
              <aside className="td-billing-note"><CreditCard size={26} /><h2>Pay as you find a fit</h2><p>Review a trainee’s goals, budget and availability for free. You only pay when you choose to open their message.</p><ul><li>One clear price before you unlock</li><li>No subscription in this concept</li><li>Follow-up messages included</li></ul><p className="td-footnote">This wireframe uses an illustrative £8 price. No payment details are collected.</p><button className="td-text-button" onClick={() => setHelp(true)}>How it works <ArrowUpRight size={14} /></button></aside></div>
          </div>}
        </>}
        <footer className="td-footer"><span>Petey. Good people, great training.</span><span>Trainer dashboard concept · v01</span></footer>
      </div>
    </main>
    {currentLead && <LeadDialog key={currentLead.id} lead={currentLead} onClose={() => setSelected(null)} onUpdate={patch => updateLead(currentLead.id, patch)} onNotify={setToast} />}
    {previewProfile && <Modal title="Your public profile preview" onClose={() => setPreviewProfile(false)}><div className="td-public-profile"><img src={johnPhoto} alt="John Kim" /><div><span className="td-status td-status--won"><ShieldCheck size={13} /> Verified trainer</span><h2>{profileToPreview.name}</h2><p>{profileToPreview.specialty} · {profileToPreview.area}</p><strong>{money(Number(profileToPreview.price))} / {profileToPreview.duration}-minute session</strong></div></div><p className="td-public-bio">{profileToPreview.bio}</p><h3>How we’ll train</h3><p>{profileToPreview.styles}</p><div className="td-tags">{profileToPreview.venues.map(venue => <span key={venue}>{venue}</span>)}</div><h3>Your training options</h3><p>{profileToPreview.serviceArea}</p><p>{profileToPreview.pricingNotes}</p><div className="td-info"><Eye size={18} /><p>{page === "profile" ? "This is a preview of your draft. Public changes appear after approval." : "This is your current approved profile in the preview."}</p></div></Modal>}
    {help && <Modal title="From a match to your next client" onClose={() => setHelp(false)}><div className="td-help-steps">{[["01", "A trainee chooses you", "Petey matches their goals and practical needs with your profile. An enquiry arrives when they choose to send you a message."], ["02", "Decide if you’re a good fit", "Review their shared goals, rough area, budget, availability and any fit differences before paying."], ["03", "Unlock the conversation", "See the exact one-off price, confirm, then read their introduction and reply. Paying opens contact; it doesn’t guarantee a client."], ["04", "Follow up and track the outcome", "Add a reminder, keep private notes and mark when someone starts training. Your outcome tracking makes your spending figures more useful."]].map(([n, title, text]) => <div key={n}><span>{n}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div><p className="td-footnote">Concept assumptions: £8 per enquiry, unlimited replies after unlock, no subscription. Pricing, cancellation and refund policy still need product decisions.</p></Modal>}
    <div className={`td-toast ${toast ? "is-visible" : ""}`} role="status">{toast && <><CheckCheck size={18} />{toast}</>}</div>
  </div>;
}

function SectionHeading({ title, subtitle, action }: { title: string; subtitle?: string; action?: ReactNode }) {
  return <div className="td-section-heading"><div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div>{action}</div>;
}
function LeadRow({ lead, onOpen, expanded = false }: { lead: Lead; onOpen: () => void; expanded?: boolean }) {
  return <button className={`td-lead-row ${expanded ? "td-lead-row--expanded" : ""}`} onClick={onOpen} aria-label={`View enquiry from ${lead.name}`}><span className={`td-initials td-initials--${Number(lead.id.split("-")[1]) % 3}`}>{lead.initials}</span><span className="td-lead-person"><strong>{lead.name}{lead.tradeoff && <span className="td-fit-note">Budget difference</span>}</strong><span>{lead.goal}</span></span><span className="td-lead-facts"><strong>{lead.budget}</strong><span>{lead.area} · {lead.venue}</span></span>{expanded && <span className="td-lead-date">{dateLabel(lead.created)}</span>}<span className={`td-status td-status--${lead.stage}`}>{lead.unlocked ? <MessageCircle size={12} /> : <LockKeyhole size={12} />}{lead.stage === "new" ? "View enquiry" : STAGE_LABELS[lead.stage]}</span><ArrowUpRight className="td-row-arrow" size={17} /></button>;
}
function EmptyLeads({ onProfile }: { onProfile: () => void }) {
  return <div className="td-empty td-empty--compact"><MessageCircle size={26} /><h3>Your next client starts here</h3><p>New enquiries will appear here when someone chooses you.</p><button className="td-text-button" onClick={onProfile}>Review your profile <ArrowRight size={15} /></button></div>;
}
function ActivityChart({ leads, period }: { leads: Lead[]; period: number }) {
  const [table, setTable] = useState(false);
  const groups = Array.from({ length: period === 28 ? 4 : 7 }, (_, i) => {
    const date = new Date(`${TODAY}T12:00:00Z`); date.setUTCDate(date.getUTCDate() - period + 1 + i * (period === 28 ? 7 : 1));
    const start = date.toISOString().slice(0, 10); date.setUTCDate(date.getUTCDate() + (period === 28 ? 7 : 1)); const end = date.toISOString().slice(0, 10);
    const received = leads.filter(l => l.created >= start && l.created < end);
    return { label: dateLabel(start), total: received.length, unlocked: received.filter(l => l.unlocked).length };
  });
  const max = Math.ceil(Math.max(4, ...groups.map(group => group.total)) / 2) * 2;
  return <section className="td-section td-activity"><SectionHeading title="Enquiry activity" subtitle="Enquiries received, and how many you’ve unlocked." action={<button className="td-text-button" onClick={() => setTable(!table)}>{table ? "Show chart" : "View data"}</button>} /><div className="td-chart-legend"><span><i /> Enquiries</span><span><i /> Unlocked</span></div>{table ? <table className="td-data-table"><caption className="sr-only">Enquiry activity by received date</caption><thead><tr><th>Received</th><th>Enquiries</th><th>Unlocked</th></tr></thead><tbody>{groups.map(g => <tr key={g.label}><th>{g.label}</th><td>{g.total}</td><td>{g.unlocked}</td></tr>)}</tbody></table> : <div className="td-chart"><div className="td-chart-scale" aria-hidden="true"><span>{max}</span><span>{Math.round(max / 2)}</span><span>0</span></div><div className="td-chart-plot">{groups.map(group => <div className="td-chart-group" key={group.label}><div className="td-chart-bars"><div className="td-bar td-bar--received" style={{ height: `${group.total / max * 100}%` }}><span>{group.total}</span></div><div className="td-bar td-bar--unlocked" style={{ height: `${group.unlocked / max * 100}%` }}><span>{group.unlocked}</span></div></div><span className="td-chart-label">{group.label}</span><span className="sr-only">: {group.total} enquiries, {group.unlocked} unlocked.</span></div>)}</div></div>}<p className="td-footnote">Grouped by enquiry received date. Unlock counts reflect their current status.</p></section>;
}

function Modal({ title, onClose, children, wide = false }: { title: string; onClose: () => void; children: ReactNode; wide?: boolean }) {
  const ref = useRef<HTMLDialogElement>(null);
  useEffect(() => { const dialog = ref.current; const trigger = document.activeElement; dialog?.showModal(); return () => { dialog?.close(); if (trigger instanceof HTMLElement && trigger.isConnected) trigger.focus(); }; }, []);
  return <dialog ref={ref} className={`td-dialog ${wide ? "td-dialog--wide" : ""}`} aria-labelledby="td-dialog-title" onCancel={e => { e.preventDefault(); onClose(); }}><div className="td-dialog-heading"><h2 id="td-dialog-title">{title}</h2><button autoFocus className="td-icon-button" aria-label="Close dialog" onClick={onClose}><X size={20} /></button></div>{children}</dialog>;
}

function LeadDialog({ lead, onClose, onUpdate, onNotify }: { lead: Lead; onClose: () => void; onUpdate: (patch: Partial<Lead>) => void; onNotify: (message: string) => void }) {
  const [checkout, setCheckout] = useState(false);
  const [failPayment, setFailPayment] = useState(false);
  const [paymentError, setPaymentError] = useState(false);
  const [message, setMessage] = useState("");
  const [note, setNote] = useState(lead.note);
  const [followUp, setFollowUp] = useState(lead.followUp ?? "");
  const [tab, setTab] = useState<"conversation" | "details">("conversation");
  const sendReply = (event: FormEvent) => { event.preventDefault(); if (!message.trim()) return; onUpdate({ messages: [...lead.messages, message.trim()], stage: lead.stage === "reply" ? "contacted" : lead.stage }); setMessage(""); onNotify("Preview reply added. No real message was sent."); };
  return <Modal title={checkout ? "Unlock this enquiry" : `Enquiry from ${lead.name.split(" ")[0]}`} onClose={onClose} wide>
    <div className="td-lead-dialog-person"><span className="td-initials">{lead.initials}</span><div><h3>{lead.name}</h3><p>{lead.goal} · {lead.area}</p></div><span className={`td-status td-status--${lead.stage}`}>{STAGE_LABELS[lead.stage]}</span></div>
    {checkout ? <div className="td-checkout"><span className="td-unlock-symbol"><LockKeyhole size={28} /></span><h3>A conversation worth starting.</h3><p>Read {lead.name.split(" ")[0]}’s introduction and follow up directly in Petey.</p><dl className="td-checkout-price"><div><dt>One enquiry unlock</dt><dd>{money(UNLOCK_PRICE)}</dd></div><div><dt>Further messages</dt><dd>Included</dd></div><div><dt>Total to pay</dt><dd>{money(UNLOCK_PRICE)}</dd></div></dl><p className="td-footnote">One-off payment. Unlocking contact doesn’t guarantee a booking.</p><div className="td-demo-payment"><CreditCard size={18} /><span>Demo checkout · No payment will be taken</span></div><label className="td-test-toggle"><input type="checkbox" checked={failPayment} onChange={e => setFailPayment(e.target.checked)} /> Test a declined payment</label>{paymentError && <p className="td-inline-error" role="alert">Payment was declined. Nothing was charged or unlocked. Turn off the test option to try again.</p>}<button className="td-button td-button--full" onClick={() => { if (failPayment) { setPaymentError(true); return; } onUpdate({ unlocked: true, unlockedAt: TODAY, stage: "reply" }); setCheckout(false); onNotify("Enquiry unlocked in the preview. No payment was taken."); }}>Simulate {money(UNLOCK_PRICE)} payment & unlock <ArrowRight size={17} /></button><button className="td-text-button" onClick={() => setCheckout(false)}>Back to enquiry</button></div> : <>
      <div className="td-lead-fact-grid">{[[Target, "Training goal", lead.goal], [Wallet, "Budget", lead.budget], [MapPin, "Training setting", `${lead.venue} · ${lead.area}`], [CalendarDays, "Availability", lead.availability]].map(([Icon, label, value]) => { const FactIcon = Icon as typeof Target; return <div key={String(label)}><FactIcon size={17} /><span><small>{String(label)}</small><strong>{String(value)}</strong></span></div>; })}</div>
      {lead.tradeoff && <div className="td-tradeoff"><CircleHelp size={19} /><p>{lead.tradeoff}</p></div>}
      {!lead.unlocked ? <><div className="td-fit-summary"><h3>Where you fit</h3><div className="td-tags">{lead.fit.map(fit => <span key={fit}><Check size={12} />{fit}</span>)}</div><p>{lead.frequency} · {lead.experience}</p></div><div className="td-locked-message"><LockKeyhole size={25} /><h3>{lead.name.split(" ")[0]} sent you a message</h3><p>Unlock to read their introduction, see their shared training brief and send your first reply.</p><div className="td-placeholder-lines" aria-hidden="true"><i /><i /><i /></div><button className="td-button" onClick={() => setCheckout(true)}>Unlock enquiry · {money(UNLOCK_PRICE)} <ArrowRight size={17} /></button><small>One-off unlock · Follow-up messages included</small></div><button className="td-text-button td-decline" onClick={() => { onUpdate({ stage: "closed" }); onNotify("Enquiry closed in this preview."); onClose(); }}>Not a fit? Close enquiry</button></> : <>
        <div className="td-conversation-tabs"><button aria-pressed={tab === "conversation"} className={tab === "conversation" ? "is-active" : ""} onClick={() => setTab("conversation")}>Conversation</button><button aria-pressed={tab === "details"} className={tab === "details" ? "is-active" : ""} onClick={() => setTab("details")}>Training brief & notes</button></div>
        {tab === "conversation" ? <><div className="td-messages" aria-live="polite"><span className="td-message-date">Enquiry received {dateLabel(lead.created).toLowerCase()}</span><div className="td-message td-message--incoming"><strong>{lead.name.split(" ")[0]}</strong><p>{lead.intro}</p></div>{lead.messages.map((text, i) => <div className="td-message td-message--outgoing" key={i}><strong>You</strong><p>{text}</p><small>Preview reply</small></div>)}</div><form className="td-composer" onSubmit={sendReply}><label className="sr-only" htmlFor="td-reply">Your reply</label><textarea id="td-reply" placeholder={`Say hello to ${lead.name.split(" ")[0]}…`} value={message} maxLength={2000} rows={3} onChange={e => setMessage(e.target.value)} /><div><span>Replies are included in your unlock.</span><button className="td-button" disabled={!message.trim()} type="submit">Send preview reply <Send size={16} /></button></div></form></> : <div className="td-brief"><h3>Their shared training brief</h3><p>{lead.brief}</p><p>{lead.frequency} · {lead.experience}</p><label className="td-field">Private notes<textarea rows={3} value={note} onChange={e => setNote(e.target.value)} placeholder="Anything useful for your next conversation…" /></label><label className="td-field">Follow-up date<input type="date" value={followUp} onChange={e => setFollowUp(e.target.value)} /></label><button className="td-button td-button--white" onClick={() => { onUpdate({ note, followUp: followUp || undefined }); onNotify("Private note and reminder saved in this preview."); }}>Save note & reminder <Check size={16} /></button></div>}
        <div className="td-lead-outcome"><label>Lead status<select aria-label="Lead status" value={lead.stage} onChange={e => { onUpdate({ stage: e.target.value as LeadStage }); onNotify("Lead status updated in this preview."); }}>{(["reply", "contacted", "consultation", "won", "closed"] as LeadStage[]).map(stage => <option key={stage} value={stage}>{STAGE_LABELS[stage]}</option>)}</select></label><span>Keep this up to date as things progress.</span></div>
      </>}
    </>}
  </Modal>;
}

function ProfileEditor({ profile, setProfile, submitted, onSave, onSubmit, onPreview }: { profile: Profile; setProfile: (profile: Profile) => void; submitted: boolean; onSave: () => void; onSubmit: () => void; onPreview: () => void }) {
  const update = (key: keyof Profile, value: string | boolean | string[]) => setProfile({ ...profile, [key]: value });
  const toggleList = (key: "venues" | "availability", value: string) => update(key, profile[key].includes(value) ? profile[key].filter(item => item !== value) : [...profile[key], value]);
  const field = (label: string, key: keyof Profile, options: { area?: boolean; type?: string; required?: boolean } = {}) => <label className="td-field">{label}{options.area ? <textarea rows={4} value={String(profile[key])} maxLength={4000} required={options.required} onChange={e => update(key, e.target.value)} /> : <input value={String(profile[key])} type={options.type ?? "text"} min={options.type === "number" ? 1 : undefined} max={options.type === "number" ? 100000 : undefined} step={options.type === "number" ? "0.01" : undefined} required={options.required} onChange={e => update(key, e.target.value)} />}</label>;
  return <div className="td-profile-editor"><form id="td-profile-form" onSubmit={e => { e.preventDefault(); onSubmit(); }}>
    {submitted && <div className="td-info td-review-banner" role="status"><Clock3 size={20} /><div><strong>Changes awaiting review</strong><p>Your approved profile stays live while we check your update. This is a simulated submission.</p></div></div>}
    <section className="td-form-section"><div className="td-form-intro"><h2>You & your coaching</h2><p>Give people a feel for the person behind the profile.</p></div><div className="td-form-fields"><div className="td-photo-field"><img src={johnPhoto} alt="Current profile photo of John Kim" /><span><strong>Your profile photo</strong><small>Use a clear, recent portrait. Photo upload is planned for the live editor.</small></span></div><div className="td-field-pair">{field("Full name", "name", { required: true })}{field("Headline specialism", "specialty", { required: true })}</div>{field("About you", "bio", { area: true, required: true })}{field("Specialisms", "specialties")}{field("Coaching style", "styles")}<div className="td-field-pair">{field("Experience", "experience")}{field("Professional website (optional)", "website", { type: "url" })}</div></div></section>
    <section className="td-form-section"><div className="td-form-intro"><h2>Where & when</h2><p>Accurate availability helps Petey make better matches.</p></div><div className="td-form-fields">{field("Your area", "area", { required: true })}{field("Where you can travel", "serviceArea", { area: true })}<fieldset className="td-choice-field"><legend>Training settings</legend><div>{["Home", "Online", "Commercial gym", "Private studio"].map(venue => <label key={venue}><input type="checkbox" checked={profile.venues.includes(venue)} onChange={() => toggleList("venues", venue)} /><span>{venue}</span></label>)}</div></fieldset><fieldset className="td-availability-grid"><legend>Typical weekly availability</legend><div className="td-week td-week--desktop"><span />{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map(day => <span key={day}>{day}</span>)}{["morning", "afternoon", "evening"].map(time => <div className="td-week-row" key={time}><span>{time[0].toUpperCase() + time.slice(1)}</span>{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map(day => <button type="button" aria-label={`${day} ${time}`} aria-pressed={profile.availability.includes(`${day}-${time}`)} className={profile.availability.includes(`${day}-${time}`) ? "is-available" : ""} onClick={() => toggleList("availability", `${day}-${time}`)} key={day}>{profile.availability.includes(`${day}-${time}`) ? <Check size={14} /> : <span aria-hidden="true">–</span>}</button>)}</div>)}</div><div className="td-week-mobile"><span>Day</span>{["Morning", "Afternoon", "Evening"].map(time => <span key={time}>{time}</span>)}{["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"].map(day => <div className="td-week-row" key={day}><span>{day}</span>{["morning", "afternoon", "evening"].map(time => <button type="button" aria-label={`${day} ${time}`} aria-pressed={profile.availability.includes(`${day}-${time}`)} className={profile.availability.includes(`${day}-${time}`) ? "is-available" : ""} onClick={() => toggleList("availability", `${day}-${time}`)} key={time}>{profile.availability.includes(`${day}-${time}`) ? <Check size={14} /> : <span aria-hidden="true">–</span>}</button>)}</div>)}</div><p className="td-footnote">Broad availability for matching. Arrange exact session times with each client.</p></fieldset><label className="td-accepting-toggle"><span><strong>Accepting new clients</strong><small>Pause new enquiries when you’re at capacity.</small></span><input type="checkbox" role="switch" checked={profile.accepting} onChange={e => update("accepting", e.target.checked)} /></label></div></section>
    <section className="td-form-section"><div className="td-form-intro"><h2>Sessions & pricing</h2><p>Set expectations before someone gets in touch.</p></div><div className="td-form-fields"><div className="td-field-pair">{field("Single session (£)", "price", { type: "number", required: true })}{field("Session length (minutes)", "duration", { type: "number", required: true })}{field("10-session package (£)", "packagePrice", { type: "number" })}{field("Monthly coaching (£)", "monthlyPrice", { type: "number" })}</div>{field("What’s included & pricing notes", "pricingNotes", { area: true })}</div></section>
    <div className="td-profile-save"><span>Public edits are reviewed before they go live.</span><button type="button" className="td-button td-button--white" onClick={onSave}>Save draft</button><button className="td-button" type="submit">Submit changes <ArrowRight size={16} /></button></div>
    </form><aside className="td-profile-aside"><div className="td-profile-preview-card"><img src={johnPhoto} alt="" /><h2>{profile.name}</h2><p>{profile.specialty}</p><small><MapPin size={13} />{profile.area}</small><strong>{money(Number(profile.price))}<small> / session</small></strong><button className="td-button td-button--white" onClick={onPreview}>Preview your profile <Eye size={15} /></button></div><section className="td-verification"><ShieldCheck size={23} /><h3>Your credentials</h3><p>Verified details build trust with the people you match with.</p><div><Check size={14} /><span>Level 3 Personal Training<small>Verified qualification</small></span></div><div><Check size={14} /><span>Coach in Running Fitness<small>Verified qualification</small></span></div><div><Check size={14} /><span>Public liability insurance<small>Example renewal · 30 Nov 2026</small></span></div><p className="td-footnote">Credential changes need a separate evidence review. This preview doesn’t upload documents.</p></section></aside></div>;
}
