import { useEffect, useState, type ChangeEvent } from "react";
import type { CredentialSubmission, ProfileWorkspace, PublicDraft } from "./model";
import { publicDraftSchema } from "./model";
import { errorMessage, filePayload, marketplace, readLocal, removeLocal, saveLocal } from "./api";
import { Modal } from "./Modal";
import { AvailabilityEditor } from "./AvailabilityEditor";

const arrayFields = { specialties: "Specialisms", coachingStyles: "Coaching style" } as const;
const settings = ["Home", "Online", "Commercial gym", "Private studio"];
export function ProfileEditor({ uid, trainerId, workspace, onChange }: { uid: string; trainerId: string; workspace: ProfileWorkspace; onChange: (profile: ProfileWorkspace) => void }) {
  const localKey = `petey.profile.${uid}`;
  const [draft, setDraft] = useState<PublicDraft>(() => readLocal(localKey, { draft: workspace.draft }).draft);
  const [baseVersion, setBaseVersion] = useState(() => readLocal(localKey, { baseVersion: workspace.baseVersion }).baseVersion);
  const [draftVersion, setDraftVersion] = useState(() => readLocal(localKey, { draftVersion: workspace.draftVersion }).draftVersion);
  const [busy, setBusy] = useState(false); const [message, setMessage] = useState(""); const [preview, setPreview] = useState(false); const [conflict, setConflict] = useState<ProfileWorkspace | null>(null);
  useEffect(() => { saveLocal(localKey, { draft, baseVersion, draftVersion }); }, [localKey, draft, baseVersion, draftVersion]);
  const set = <K extends keyof PublicDraft>(key: K, value: PublicDraft[K]) => setDraft(old => ({ ...old, [key]: value }));
  async function save(publish: boolean) {
    setBusy(true); setMessage("");
    try {
      const parsed = publicDraftSchema.safeParse(draft); if (!parsed.success) throw new Error(parsed.error.issues[0]?.message ?? "Check your profile fields.");
      let result = await marketplace<ProfileWorkspace>({ action: "draft", draft: parsed.data, expectedDraftVersion: draftVersion, baseVersion });
      setDraftVersion(result.draftVersion); onChange(result);
      if (publish) result = await marketplace<ProfileWorkspace>({ action: "publish", expectedVersion: baseVersion, expectedDraftVersion: result.draftVersion });
      setBaseVersion(result.baseVersion); onChange(result); setConflict(null); removeLocal(localKey); setMessage(publish ? "Your profile is now published." : "Draft saved. Your public profile is unchanged.");
    } catch (e) { setMessage(errorMessage(e)); if ((e as { code?: string }).code === "functions/aborted") setConflict(await marketplace<ProfileWorkspace>({ action: "profile" })); }
    finally { setBusy(false); }
  }
  async function photo(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0]; if (!file) return;
    setBusy(true); setMessage(""); try {
      const result = await marketplace<ProfileWorkspace>({ action: "photo", file: await filePayload(file), expectedDraftVersion: draftVersion });
      setDraftVersion(result.draftVersion); onChange(result); setMessage("Photo saved to your draft. Publish when you’re ready.");
    } catch (e) { setMessage(errorMessage(e)); } finally { setBusy(false); event.target.value = ""; }
  }
  return <div className="mp-profile-layout"><form className="mp-panel mp-profile-form" onSubmit={event => { event.preventDefault(); void save(true); }}><div className="mp-profile-photo"><img src={workspace.draftPhotoUrl} alt="Your draft profile" /><div><h2>Make it feel like you</h2><label className="td-text-button">Replace photo<input type="file" accept="image/jpeg,image/png,image/webp" disabled={busy} onChange={event => void photo(event)} /></label><small>JPEG, PNG or WebP · up to 5 MB</small></div></div>
    <fieldset><legend>Your introduction</legend><label>Full name<input required maxLength={160} value={draft.name} onChange={event => set("name", event.target.value)} /></label><label>About you<textarea required rows={5} maxLength={4000} value={draft.bio} onChange={event => set("bio", event.target.value)} /></label><div className="mp-fields"><label>Experience<input maxLength={160} value={draft.experience} onChange={event => set("experience", event.target.value)} /></label><label>Professional website<input type="url" placeholder="https://" value={draft.professionalUrl ?? ""} onChange={event => set("professionalUrl", event.target.value || null)} /></label><label>Gender (optional)<input maxLength={160} value={draft.gender ?? ""} onChange={event => set("gender", event.target.value || null)} /></label></div></fieldset>
    <fieldset><legend>How you coach</legend>{Object.entries(arrayFields).map(([key, label]) => <label key={key}>{label}<textarea rows={3} value={draft[key as keyof typeof arrayFields].join("\n")} onChange={event => set(key as keyof typeof arrayFields, event.target.value.split("\n"))} /><small>One item per line. Keep any free-form availability or service notes that help trainees understand your offer.</small></label>)}</fieldset>
    <fieldset><legend>Where and when</legend><h3>Training settings</h3><div className="mp-fields">{settings.map(setting => <label className="mp-checkbox" key={setting}><input type="checkbox" checked={draft.venues.includes(setting)} onChange={event => set("venues", event.target.checked ? [...draft.venues, setting] : draft.venues.filter(item => item !== setting))} />{setting}</label>)}</div><label>Other training settings<textarea value={draft.venues.filter(item => !settings.includes(item)).join("\n")} onChange={event => set("venues", [...draft.venues.filter(item => settings.includes(item)), ...event.target.value.split("\n").filter(Boolean)])} /></label><AvailabilityEditor value={draft.availability} onChange={value => set("availability", value)} /><label>Area<input required maxLength={160} value={draft.area} onChange={event => set("area", event.target.value)} /></label><label>Service-area notes<textarea maxLength={4000} value={draft.serviceAreaNotes} onChange={event => set("serviceAreaNotes", event.target.value)} /></label><label>Available from<input type="date" value={draft.availableFrom ?? ""} onInput={event => set("availableFrom", event.currentTarget.value || null)} onChange={event => set("availableFrom", event.target.value || null)} /></label><label className="mp-checkbox"><input type="checkbox" checked={draft.acceptingNewClients} onChange={event => set("acceptingNewClients", event.target.checked)} /> Accepting new clients when this draft publishes</label></fieldset>
    <fieldset><legend>Your pricing</legend><div className="mp-fields">{(["singleSessionPence", "tenPackPence", "monthlyCoachingPence"] as const).map((key, index) => <label key={key}>{["Single session (£)", "10-session pack (£)", "Monthly coaching (£)"][index]}<input type="number" min="0" step="0.01" value={draft[key] === null ? "" : draft[key] / 100} onChange={event => set(key, event.target.value === "" ? null : Math.round(Number(event.target.value) * 100))} /></label>)}<label>Session length (minutes)<input type="number" min="1" max="1440" value={draft.sessionDurationMinutes ?? ""} onChange={event => set("sessionDurationMinutes", event.target.value ? Number(event.target.value) : null)} /></label></div><label>Pricing notes<textarea maxLength={4000} value={draft.pricingNotes} onChange={event => set("pricingNotes", event.target.value)} /></label></fieldset>
    {conflict && <section className="mp-conflict"><h3>A newer profile is available</h3><p>Your edits are kept above. Review the latest published content below before combining changes.</p><details><summary>Compare latest published profile and saved draft</summary><pre>{JSON.stringify({ published: conflict.published, savedDraft: conflict.draft }, null, 2)}</pre></details><button className="td-button td-button--white" type="button" onClick={() => { setBaseVersion(conflict.version); setDraftVersion(conflict.draftVersion); onChange(conflict); setConflict(null); setMessage("Your local edits are kept. Save or publish your combined version when ready."); }}>Keep my edits and use this version as the baseline</button></section>}
    <p role="status" className="mp-notice">{message || "Edits are saved on this device as you type. Public changes publish immediately; credentials are reviewed separately."}</p><div className="mp-form-actions"><button className="td-button td-button--white" type="button" disabled={busy} onClick={() => setPreview(true)}>Preview</button><button className="td-button td-button--white" type="button" disabled={busy} onClick={() => void save(false)}>Save draft</button><button className="td-button" type="submit" disabled={busy}>{busy ? "Saving…" : "Publish changes"}</button></div>
  </form><aside><Credentials trainerId={trainerId} workspace={workspace} /></aside>{preview && <Modal title="Your profile preview" onClose={() => setPreview(false)}><img className="mp-preview-photo" src={workspace.draftPhotoUrl} alt={draft.name} /><h3>{draft.name}</h3><p>{draft.area} · {draft.specialties.join(" · ")}</p><p className="mp-preserve">{draft.bio}</p><p>{draft.coachingStyles.join(" · ")}</p><p>{draft.venues.join(" · ")}</p><p>{draft.availability.join(" · ")}</p><p>{draft.singleSessionPence !== null ? `£${draft.singleSessionPence / 100} per session` : "Session price not set"}</p></Modal>}</div>;
}
function Credentials({ trainerId, workspace }: { trainerId: string; workspace: ProfileWorkspace }) {
  const [items, setItems] = useState<CredentialSubmission[]>([]); const [kind, setKind] = useState<"qualification" | "insurance">("qualification");
  const [title, setTitle] = useState(""); const [provider, setProvider] = useState(""); const [expiry, setExpiry] = useState(""); const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false); const [requestId, setRequestId] = useState(() => crypto.randomUUID());
  useEffect(() => { void marketplace<CredentialSubmission[]>({ action: "credentialList", trainerId }).then(setItems).catch(e => setMessage(errorMessage(e))); }, [trainerId]);
  return <section className="mp-panel"><h2>Your credentials</h2><p>{workspace.qualifications.join(" · ")}</p><p className="mp-notice">Verification expiry: {workspace.verificationExpiresOn ?? "No expiry recorded"}. Current valid credentials remain active while replacements are reviewed.</p><ul className="mp-credential-list">{items.map(item => <li key={item.id}><strong>{item.title}</strong><span>{item.status}</span>{item.reason && <p>{item.reason}</p>}</li>)}</ul><h3>Submit replacement evidence</h3><form onSubmit={async event => { event.preventDefault(); if (!file) return; setBusy(true); setMessage(""); try { await marketplace({ action: "credentials", kind, title, provider, expiresOn: expiry || null, file: await filePayload(file), requestId }); setItems(await marketplace<CredentialSubmission[]>({ action: "credentialList", trainerId })); setRequestId(crypto.randomUUID()); setMessage("Evidence submitted for review."); } catch (e) { setMessage(errorMessage(e)); } finally { setBusy(false); } }}><label>Type<select value={kind} onChange={event => setKind(event.target.value as typeof kind)}><option value="qualification">Qualification</option><option value="insurance">Insurance</option></select></label><label>Title<input required maxLength={160} value={title} onChange={event => setTitle(event.target.value)} /></label><label>Provider<input required maxLength={160} value={provider} onChange={event => setProvider(event.target.value)} /></label><label>Expiry date<input type="date" required={kind === "insurance"} value={expiry} onInput={event => setExpiry(event.currentTarget.value)} onChange={event => setExpiry(event.target.value)} /></label><label>Evidence file<input type="file" required accept="application/pdf,image/jpeg,image/png,image/webp" onChange={event => setFile(event.target.files?.[0] ?? null)} /><small>PDF or image · up to 5 MB</small></label><button className="td-button td-button--white" disabled={busy}>Submit for review</button><p role="status">{message}</p></form></section>;
}
