import { useCallback, useEffect, useRef, useState } from "react";
import type { ApplicationDetail } from "../features/trainerApplications/model";
import type { CredentialSubmission, InvitationStatus } from "../features/marketplace/model";
import type { ReviewApi } from "./api";
import { reviewErrorMessage } from "./auth";

export function TrainerPilotControls({ detail, api, disabled, onUpdated }: { detail: ApplicationDetail; api: ReviewApi; disabled: boolean; onUpdated: (detail: ApplicationDetail) => void }) {
  const [status, setStatus] = useState<InvitationStatus | null>(null); const [submissions, setSubmissions] = useState<CredentialSubmission[]>([]); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const [checked, setChecked] = useState<Record<string, boolean>>({}); const [reasons, setReasons] = useState<Record<string, string>>({}); const inviteId = useRef(crypto.randomUUID());
  const load = useCallback(async () => { const [invitation, credentials] = await Promise.all([api.marketplace!<InvitationStatus>({ action: "invitationStatus", trainerId: detail.application.id }), api.marketplace!<CredentialSubmission[]>({ action: "credentialList", trainerId: detail.application.id })]); setStatus(invitation); setSubmissions(credentials); }, [api, detail.application.id]);
  useEffect(() => { let alive = true; void Promise.all([api.marketplace!<InvitationStatus>({ action: "invitationStatus", trainerId: detail.application.id }), api.marketplace!<CredentialSubmission[]>({ action: "credentialList", trainerId: detail.application.id })]).then(([invitation, credentials]) => { if (alive) { setStatus(invitation); setSubmissions(credentials); } }).catch(error => { if (alive) setMessage(reviewErrorMessage(error)); }); return () => { alive = false; }; }, [api, detail.application.id]);
  return <section className="review-section"><h2>Trainer pilot access</h2><p>Invitation: <strong>{status?.status ?? "Loading…"}</strong>{status?.email ? ` · ${status.email}` : ""}</p>{status?.expiresAt && <p>Expires {new Date(status.expiresAt).toLocaleString("en-GB")}</p>}
    <div className="review-actions">{status?.status !== "accepted" && !status?.uid && <button type="button" className="review-primary" disabled={disabled || busy || detail.application.status !== "approved"} onClick={async () => { setBusy(true); setMessage(""); try { setStatus(await api.marketplace!({ action: "invite", trainerId: detail.application.id, requestId: inviteId.current })); inviteId.current = crypto.randomUUID(); setMessage("Invitation queued. Delivery depends on the configured email service; previous invitation links are invalidated."); } catch (error) { setMessage(reviewErrorMessage(error)); } finally { setBusy(false); } }}>{status?.status === "none" ? "Invite trainer" : "Resend invitation"}</button>}{status && !["none", "revoked"].includes(status.status) && <button type="button" disabled={disabled || busy} onClick={async () => { if (!window.confirm("Revoke this trainer’s invitation and workspace access?")) return; setBusy(true); try { setStatus(await api.marketplace!({ action: "revoke", trainerId: detail.application.id })); setMessage("Trainer access revoked."); } catch (error) { setMessage(reviewErrorMessage(error)); } finally { setBusy(false); } }}>Revoke access</button>}</div>
    <p className="review-hint">Only approved web applicants can be invited. Links expire after seven days and require the invited email. After acceptance, public profile edits belong to the trainer; later form approvals preserve that content.</p>
    <h3>Replacement credentials</h3>{submissions.length === 0 ? <p>No replacement evidence submitted.</p> : submissions.map(item => <div className="review-checklist" key={item.id}><h4>{item.title} · {item.status}</h4><p>{item.provider} · expiry {item.expiresOn ?? "not specified"}</p>{item.url && <a href={item.url} target="_blank" rel="noreferrer">Open private evidence</a>}{item.status === "pending" && <><label className="review-check"><input type="checkbox" checked={checked[item.id] ?? false} onChange={event => setChecked(old => ({ ...old, [item.id]: event.target.checked }))} /> I checked this replacement evidence and its dates</label><label>Review reference / decision reason<textarea maxLength={2000} value={reasons[item.id] ?? ""} onChange={event => setReasons(old => ({ ...old, [item.id]: event.target.value }))} /></label><div className="review-actions">{[true, false].map(approve => <button key={String(approve)} disabled={busy || disabled || !(reasons[item.id]?.trim()) || (approve && !checked[item.id])} onClick={async () => { setBusy(true); try { const verification = structuredClone(detail.verification); const replacement = { provider: item.provider, expiresOn: item.expiresOn, reference: reasons[item.id], checked: true }; if (item.kind === "qualification") verification.qualification = { ...replacement, title: item.title }; else verification.insurance = replacement; await api.marketplace!({ action: "credentialReview", trainerId: detail.application.id, submissionId: item.id, approve, reason: reasons[item.id], verification, expectedVersion: detail.application.version }); onUpdated(await api.detail(detail.application.id)); await load(); setMessage(approve ? "Replacement credential approved. Trainer-authored public content has been preserved." : "Replacement rejected. Existing credentials are unchanged."); } catch (error) { setMessage(reviewErrorMessage(error)); } finally { setBusy(false); } }}>{approve ? "Approve replacement" : "Reject replacement"}</button>)}</div></>}</div>)}<p role="status">{message}</p>
  </section>;
}
